#!/bin/bash

case $1 in
"start"){
        echo ================== 启动 集群 ==================

	   #启动 Hadoop集群
        myhadoop start

        #启动 Zookeeper集群
        zk start

        #启动 Kafka采集集群
        kf start

        #启动 Flume采集集群
        fl1 start

        #启动 Flume消费集群
        fl2 start

        };;
"stop"){
        echo ================== 停止 集群 ==================

        #停止 Flume消费集群
        fl2 stop

        #停止 Flume采集集群
        fl1 stop

        #停止 Kafka采集集群
        kf stop

        #停止 Hadoop集群
        myhadoop stop

        #停止 Zookeeper集群
        zk stop

};;
esac
