#! /bin/bash

case $1 in
"start"){
    for((host=101;host<104;host++));
    do
        echo " --------启动 $host Kafka-------"
        ssh hadoop$host "/export/servers/kafka/bin/kafka-server-start.sh -daemon /export/servers/kafka/config/server.properties"
    done
};;
"stop"){
    for((host=101;host<104;host++));
    do
        echo " --------停止 $host Kafka-------"
        ssh hadoop$host "/export/servers/kafka/bin/kafka-server-stop.sh stop"
    done
};;
esac
